[project]
name = "video-recommender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nan Phyu Sin Maung", email = "nanphyusinmg@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastparquet>=2026.9.0",
    "jupyter>=1.1.1",
    "kafka-python>=3.0.11",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas<3",
    "pyspark>=4.2.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "supabase>=2.31.0",
]

[project.scripts]
video-recommender = "video_recommender:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
